const { MongoClient } = require('mongodb');
const uri = 'mongodb+srv://rhythmgoel9:hjIIaC3iwRadR7pl@cluster0.qgdtyex.mongodb.net/campusbuzz?appName=Cluster0';
async function run() {
  const client = new MongoClient(uri);
  await client.connect();
  const col = client.db('campusbuzz').collection('events');
  const toDelete = ['crossroads-mun-2026','dumun-2026','aurexis-gargi-2026','voices-today-daulat-ram-2026','reconovate-gargi-2026','enactopia-aryabhatta-2026','hindu-stock-exchange-2026','engifest-2026','spandhan-2026','engifest-bob-2026','national-space-hackathon-2026','hindu-policy-case-2026','potentate-2026','tryst-iit-delhi-2026','crossroads-2026','mecca-2026','hackdtu-2026','invictus-dtu-2026'];
  const del = await col.deleteMany({ slug: { $in: toDelete } });
  console.log('Deleted:', del.deletedCount);
  const newEvents = [
    {slug:'tempest-miranda-2026',name:'Tempest 2026 — Miranda House Annual Fest',college:'Miranda House, University of Delhi',cat:'fest',date:'Mar 29, 2026',dateStart:'2026-03-29',desc:'Annual cultural extravaganza of Miranda House DU featuring dance, music, drama and DJ night.',regLink:'https://unstop.com',hot:true,tags:['dance','music','drama']},
    {slug:'alma-fiesta-jmi-2026',name:'Alma Fiesta 2026 — Jamia Millia Islamia',college:'Jamia Millia Islamia',cat:'fest',date:'Mar 27-29, 2026',dateStart:'2026-03-27',desc:'JMI mega annual cultural fest with 3 days of performances, competitions and celebrity appearances.',regLink:'https://unstop.com',hot:true,tags:['cultural','music','dance']},
    {slug:'synergy-dse-2026',name:'Synergy 2026 — Delhi School of Economics Fest',college:'Delhi School of Economics, DU',cat:'fest',date:'Mar 25-26, 2026',dateStart:'2026-03-25',desc:'DSE flagship annual fest with case competitions, cultural events and guest lectures.',regLink:'https://unstop.com',hot:false,tags:['economics','debate','case']},
    {slug:'aaveg-dtu-2026',name:'Aaveg 2026 — DTU Annual Dance Fest',college:'Delhi Technological University',cat:'dance',date:'Apr 18-19, 2026',dateStart:'2026-04-18',desc:'DTU flagship inter-college dance competition. Solo, duet and group categories. Prizes worth Rs 75K.',regLink:'https://unstop.com',hot:true,tags:['classical','western','fusion'],prize:'Rs 75,000'},
    {slug:'hackcbs-2026',name:'hackCBS 3.0 — India Largest Student Hackathon',college:'Shaheed Sukhdev College of Business Studies, DU',cat:'tech',date:'Apr 12-13, 2026',dateStart:'2026-04-12',desc:'24-hour hackathon by SSCBS. MLH member event. 1000+ hackers, massive prizes and mentorship.',regLink:'https://unstop.com/hackathons/hackcbs-30-indias-largest-student-run-hackathon-shaheed-sukhdev-college-of-business-studies-sscbs-university-of-delhi--127818',hot:true,tags:['hackathon','24hr','MLH'],prize:'$220,000+'},
    {slug:'e-raksha-iit-2026',name:'E-Raksha Hackathon 2026 — IIT Delhi',college:'IIT Delhi',cat:'tech',date:'Apr 5-6, 2026',dateStart:'2026-04-05',desc:'Cybersecurity hackathon by IIT Delhi. Build solutions in digital security and ethical hacking.',regLink:'https://unstop.com',hot:true,tags:['cybersecurity','hackathon','IIT'],prize:'Rs 1,00,000+'},
    {slug:'robowars-nit-2026',name:'Robowars Delhi 2026 — NIT Delhi',college:'NIT Delhi',cat:'tech',date:'Apr 25, 2026',dateStart:'2026-04-25',desc:'Combat robotics championship where student-built robots battle. Prizes worth Rs 50K+.',regLink:'https://unstop.com',hot:true,tags:['robotics','combat','engineering'],prize:'Rs 50,000+'},
    {slug:'sportech-nsut-2026',name:'Sportech 2026 — NSUT Annual Sports Meet',college:'Netaji Subhas University of Technology',cat:'fest',date:'Apr 8-10, 2026',dateStart:'2026-04-08',desc:'Inter-college sports meet featuring cricket, football, basketball and esports.',regLink:'https://unstop.com',hot:false,tags:['cricket','football','esports'],prize:'Rs 30,000+'},
    {slug:'hansraj-mun-2026',name:'Hansraj MUN 2026 — Statecraft',college:'Hansraj College, University of Delhi',cat:'mun',date:'Apr 11-12, 2026',dateStart:'2026-04-11',desc:'Two-day MUN by Statecraft Hansraj. Committees include UNSC, UNHRC and crisis committee.',regLink:'https://www.dublieu.com/mun-tracker',hot:true,tags:['UNSC','UNHRC','diplomacy']},
    {slug:'nsut-mun-2026',name:'NSUT MUN 2026 — MUNSOC NSUT',college:'Netaji Subhas University of Technology',cat:'mun',date:'Apr 11-12, 2026',dateStart:'2026-04-11',desc:'Annual MUN by MUNSOC NSUT with multiple committees and crisis simulations.',regLink:'https://www.dublieu.com/mun-tracker',hot:false,tags:['MUN','diplomacy','debate']},
    {slug:'confero-mun-2026',name:'Confero MUN 2026 — SGTB Khalsa',college:'SGTB Khalsa College, DU',cat:'mun',date:'Apr 4-5, 2026',dateStart:'2026-04-04',desc:'Flagship MUN by MUNSOC SGTB Khalsa. UNGA, UNHRC and press corps committees.',regLink:'https://www.dublieu.com/mun-tracker',hot:false,tags:['UNGA','UNHRC','press']},
    {slug:'delhi-youth-dialogue-2026',name:'Delhi Youth Dialogue MUN 2026',college:'Delhi NCR',cat:'mun',date:'Apr 30 - May 1, 2026',dateStart:'2026-04-30',desc:'MUN featuring NATO and HUNSC committees. Focus on Ukraine-Russia and nuclear proliferation.',regLink:'https://www.dublieu.com/muns/delhi-youth-dialogue-2026',hot:false,tags:['NATO','HUNSC','crisis']},
    {slug:'kiet-mun-2026',name:'KIET MUN 2026',college:'KIET Group of Institutions, Ghaziabad',cat:'mun',date:'Mar 28-29, 2026',dateStart:'2026-03-28',desc:'Two-day MUN by MUNSOC KIET. UNSC, WHO and All India Political Parties Meet committees.',regLink:'https://www.dublieu.com/mun-tracker',hot:false,tags:['UNSC','WHO','diplomacy']},
    {slug:'mushaira-hindu-2026',name:'Mushaira 2026 — Hindu College Literary Fest',college:'Hindu College, University of Delhi',cat:'literary',date:'Apr 7, 2026',dateStart:'2026-04-07',desc:'Annual Urdu poetry festival by Hindu College featuring renowned poets and open mic sessions.',regLink:'https://unstop.com',hot:false,tags:['poetry','urdu','spoken word']},
    {slug:'rendezvous-iit-2026',name:'Rendezvous 2026 — IIT Delhi Cultural Fest',college:'IIT Delhi',cat:'concert',date:'Oct 2026',dateStart:'2026-10-01',desc:'North India largest college cultural festival. 4 days of concerts, competitions and 50,000+ footfall.',regLink:'https://rendezvous.iitd.ac.in',hot:false,tags:['concert','celebrity','cultural']},
    {slug:'igmc-dance-2026',name:'Roobaroo 2026 — IGDTUW Dance Fest',college:'Indira Gandhi Delhi Technical University for Women',cat:'dance',date:'Apr 10, 2026',dateStart:'2026-04-10',desc:'Annual inter-college dance competition by IGDTUW. Western, classical and freestyle categories. Open to all.',regLink:'https://unstop.com',hot:false,tags:['dance','western','classical'],prize:'Rs 25,000'},
    {slug:'gargi-fest-2026',name:'Mimansa 2026 — Gargi College Annual Fest',college:'Gargi College, University of Delhi',cat:'fest',date:'Apr 3-4, 2026',dateStart:'2026-04-03',desc:'Gargi College annual cultural fest with competitions, workshops, celebrity performances and DJ night.',regLink:'https://unstop.com',hot:true,tags:['cultural','music','workshops']},
  ];
  const ins = await col.insertMany(newEvents);
  console.log('Inserted:', ins.insertedCount);
  const all = await col.find({},{projection:{slug:1,name:1,date:1,cat:1}}).sort({dateStart:1}).toArray();
  console.log('\n=== ALL EVENTS ===');
  all.forEach(e => console.log(e.cat.padEnd(12), e.date.padEnd(22), e.name));
  await client.close();
}
run().catch(console.error);
