// lib/seed.js — populate MongoDB with initial events
// Run: MONGODB_URI="..." node lib/seed.js
require('dotenv').config({ path: require('path').join(__dirname, '../.env.local') });
const { connectDB } = require('./mongodb');
const Event = require('../models/Event');

const EVENTS = [
  { slug:'engifest-2026', cat:'fest', name:'Engifest 2026 — DTU Cultural Fest', college:'Delhi Technological University', date:'Mar 21–23, 2026', time:'10:00 AM', venue:'DTU Campus, Rohini', prize:'₹5,00,000', free:false, hot:true, tags:['Music','Dance','Drama','ProNight','Comedy'], deadline:new Date('2026-03-20'), registrations:12400, description:"DTU's legendary 3-day cultural extravaganza. Battle of Bands, dance battles, comedy acts, fashion protests and a blockbuster Pro Night.", verified:true },
  { slug:'spandhan-2026', cat:'dance', name:'Engifest Dance — Spandhan 2026', college:'Delhi Technological University', date:'Mar 23, 2026', time:'10:00 AM', venue:'BR Auditorium, DTU', prize:'₹31,000', free:false, hot:true, tags:['Bollywood','Hip-Hop','Fusion','Group'], deadline:new Date('2026-03-19'), registrations:780, description:"Spandhan by Vibe — DTU's flagship group dance competition. All styles welcome.", verified:true },
  { slug:'crossroads-2026', cat:'concert', name:"Crossroads '26 — SRCC Golden Jubilee", college:'Shri Ram College of Commerce, DU', date:'Mar 16–18, 2026', time:'5:00 PM', venue:'SRCC Campus, North Campus DU', prize:'₹0', free:true, hot:true, tags:['50th Anniversary','Live Music','Business','ProNight'], deadline:new Date('2026-03-15'), registrations:9800, description:"SRCC's 50th edition — DU's most iconic business-culture hybrid fest. 500+ colleges, celebrity headliners.", verified:true },
  { slug:'crossroads-mun-2026', cat:'mun', name:'Crossroads MUN 2026', college:'Shri Ram College of Commerce, DU', date:'Mar 16, 2026', time:'9:00 AM', venue:'SRCC Main Block, Delhi', prize:'₹40,000', free:false, hot:false, tags:['UNSC','G20','Business Council','Crisis'], deadline:new Date('2026-03-10'), registrations:520, description:'High-stakes MUN at DU\'s most prestigious commerce college. Business and geopolitical committees.', verified:true },
  { slug:'rendezvous-2026', cat:'fest', name:'Rendezvous 2026 — IIT Delhi', college:'IIT Delhi', date:'Oct 2–5, 2026', time:'10:00 AM', venue:'IIT Delhi, Hauz Khas', prize:'₹20,00,000', free:false, hot:true, tags:['ProNight','Cultural','Sports','Workshops'], deadline:new Date('2026-09-28'), registrations:15000, description:"Asia's largest student cultural festival. 160,000+ participants, 5 legendary nights.", verified:true },
  { slug:'tempest-2026', cat:'dance', name:'Tempest 2026 — Miranda House Fest', college:'Miranda House, DU', date:'Mar 29, 2026', time:'3:00 PM', venue:'Miranda House Amphitheatre, DU', prize:'₹80,000', free:false, hot:false, tags:['Battle of Bands','Stage Play','Folk Dance','Izhar'], deadline:new Date('2026-03-25'), registrations:650, description:"Miranda House's iconic cultural fest. Izhar stage play, Battle of Bands, Tarangini folk dance.", verified:true },
  { slug:'hackdtu-2026', cat:'tech', name:'HackDTU 2026 — 36hr Hackathon', college:'DTU, Rohini', date:'Apr 18–19, 2026', time:'10:00 AM', venue:'DTU Innovation Hub', prize:'₹3,00,000', free:false, hot:true, tags:['AI/ML','Web3','IoT','36hrs','Google'], deadline:new Date('2026-04-14'), registrations:2200, description:"Delhi's biggest 36-hour hackathon. AI, Web3, IoT tracks. Mentors from Google, Microsoft, Razorpay.", verified:true },
  { slug:'engifest-bob-2026', cat:'music', name:'Engifest Battle of Bands 2026', college:'Delhi Technological University', date:'Mar 22, 2026', time:'5:00 PM', venue:'OAT Stage, DTU', prize:'₹50,000', free:false, hot:true, tags:['Rock','Metal','Indie','Live Band'], deadline:new Date('2026-03-18'), registrations:420, description:'DTU\'s legendary Battle of Bands. Rock, metal, indie, fusion. Past headliners: Nucleya, Divine, Amit Trivedi.', verified:true },
  { slug:'mecca-2026', cat:'fest', name:'Mecca 2026 — Hindu College Annual Fest', college:'Hindu College, DU', date:'Apr 5–6, 2026', time:'11:00 AM', venue:'Hindu College, North Campus', prize:'₹2,00,000', free:true, hot:true, tags:['Gully Cricket','Street Dance','Fashion','Live Music'], deadline:new Date('2026-04-02'), registrations:6800, description:"Hindu College's crown fest. 70,000+ crowd. Gully Cricket, street dance and fashion show.", verified:true },
  { slug:'mushaira-2026', cat:'literary', name:"Musha'irah — Hindu College Lit Fest", college:'Hindu College, DU', date:'Apr 7, 2026', time:'6:00 PM', venue:'Hindu College Main Hall', prize:'₹25,000', free:false, hot:false, tags:['Slam Poetry','Urdu','Hindi','Author Conclave'], deadline:new Date('2026-04-04'), registrations:340, description:"Hindu College's annual literature festival. Slam poetry, author conclaves with renowned novelists.", verified:true },
  { slug:'dumun-2026', cat:'mun', name:'Delhi University MUN 2026', college:'Hindu College, Delhi', date:'Mar 10–12, 2026', time:'9:00 AM', venue:'Hindu College, DU', prize:'₹60,000', free:false, hot:false, tags:['UNGA','UNSC','Crisis','Historical'], deadline:new Date('2026-03-05'), registrations:1400, description:'DU\'s most prestigious MUN. 15 committees, 1500+ delegates from 300+ colleges.', verified:true },
  { slug:'robowars-2026', cat:'tech', name:'Robowars Delhi 2026 — NIT', college:'NIT Delhi, Narela', date:'Apr 25, 2026', time:'10:00 AM', venue:'NIT Delhi Campus', prize:'₹1,50,000', free:false, hot:true, tags:['Robotics','Combat','15kg','60kg'], deadline:new Date('2026-04-20'), registrations:580, description:'Heavyweight robot combat at NIT Delhi. Design, build and destroy.', verified:true },
];

async function seed() {
  await connectDB();
  await Event.deleteMany({});
  const inserted = await Event.insertMany(EVENTS);
  console.log(`✅  Seeded ${inserted.length} events into MongoDB`);
  process.exit(0);
}

seed().catch(err => { console.error('❌ Seed failed:', err.message); process.exit(1); });
